### ISSUE TITLE
加载的时候，好慢，有时候加载不出来

### ISSUE THREAD

**Issue by yuang01** [xiarimangguo/aLive2D#1]

**Comment by xiarimangguo** [comment]
是不是你的网络问题呢？模型加载需要一定时间的，尝试开启服务器缓存，或者压缩一下texture.png试一下吧！请把你的截图发一下，谢谢

**Comment by yuang01** [comment]
![TT(9Q7JPLZEUM 3RRJ_MKGW](https://user-images.githubusercontent.com/32896990/128161973-792be81f-6862-4a68-8ddd-255c68046bcd.png)
![CD}T4OV7A80 F}E`BWOQDVS](https://user-images.githubusercontent.com/32896990/128162012-3e205b3a-5273-49f6-b288-26be78f14bf3.png)
这样子的

**Comment by xiarimangguo** [comment]
用的是示例api吗？不过我这里没问题啊，应该是你的网络问题吧！
![Screenshot_20210804_180535](https://user-images.githubusercontent.com/38160007/128164072-9960818a-a52e-4c6d-b4a4-99cf19ff2e0e.JPG)
抱歉，我这里github连接不稳定，图片上传总是失败

**Comment by xiarimangguo** [comment]
![Screenshot_20210804_180307](https://user-images.githubusercontent.com/38160007/128164439-c155160e-6b0d-42ff-b4f0-96e2de72a1f1.JPG)
显示正常啊

**Comment by yuang01** [comment]
好吧，我下回试一下自己搭建api

**Comment by xiarimangguo** [comment]
好的，那我先关闭这个issues了
